'use strict';
// DOM-event integration harness, NOT a browser or graphical verification.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {Worker:Thread}=require('node:worker_threads');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const script=id=>html.match(new RegExp('<script\\b[^>]*id="'+id+'"[^>]*>([\\s\\S]*?)<\\/script>'))[1];
const blobs=new Map(),downloads=[],elements=new Map(),workers=new Set();let blobId=0,terminated=0;
class LocalBlob{constructor(parts,options){this.textValue=parts.map(p=>p instanceof LocalBlob?p.textValue:String(p)).join('');this.type=options?.type||'';}}
const context2d=new Proxy({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)})},{get:(o,k)=>k in o?o[k]:(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
class Element{
 constructor(tag='div',id=''){this.tagName=tag.toUpperCase();this.id=id;this.value='';this.checked=false;this.disabled=false;this.children=[];this.dataset={};this.style={setProperty(name,value){this[name]=value;}};this.listeners={};this.textContent='';this.clientWidth=240;this.clientHeight=170;this.labels=[{textContent:id}];this.offsetWidth=80;this.offsetHeight=40;}
 addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}
 async fire(name,event={}){event.preventDefault??=()=>{};if(this['on'+name])await this['on'+name](event);for(const fn of this.listeners[name]||[])await fn(event);}
 click(){if(this.tagName==='A')downloads.push({name:this.download,blob:blobs.get(this.href)});else if(!this.disabled)return this.fire('click');}
 append(...nodes){this.children.push(...nodes);}
 replaceChildren(...nodes){this.children=nodes;if(this.tagName==='SELECT')this.value=nodes[0]?.value||'';}
 setAttribute(){}remove(){}setPointerCapture(){}getBoundingClientRect(){return{left:0,top:0};}
 getContext(){return context2d;}toBlob(fn){fn(new LocalBlob(['mock-png'],{type:'image/png'}));}
 closest(){return{querySelector:()=>pngButtons.find(b=>b.dataset.png===this.id)}}
}
for(const m of html.matchAll(/<([a-z][a-z0-9-]*)\b([^>]*\bid="([^"]+)"[^>]*)>/gi)){
 const el=new Element(m[1],m[3]),attrs=m[2];el.value=attrs.match(/\bvalue="([^"]*)"/)?.[1]||'';el.checked=/\bchecked\b/.test(attrs);el.disabled=/\bdisabled\b/.test(attrs);elements.set(el.id,el);
}
for(const m of html.matchAll(/<select\b[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/select>/gi)){
 const opts=Array.from(m[2].matchAll(/<option\b([^>]*)>/g),q=>({value:q[1].match(/value="([^"]*)"/)?.[1]||'',selected:/\bselected\b/.test(q[1])}));elements.get(m[1]).value=(opts.find(o=>o.selected)||opts[0])?.value||'';
}
const pngButtons=Array.from(html.matchAll(/<button\b[^>]*data-png="([^"]+)"[^>]*>/g),m=>{const e=new Element('button');e.dataset.png=m[1];return e;});
const resetButtons=Array.from(html.matchAll(/<button\b[^>]*data-reset="([^"]+)"[^>]*>/g),m=>{const e=new Element('button');e.dataset.reset=m[1];return e;});
const document={getElementById:id=>{assert.ok(elements.has(id),'Unknown DOM id '+id);return elements.get(id);},createElement:tag=>new Element(tag),body:new Element('body'),querySelectorAll:s=>s==='[data-png]'?pngButtons:s==='[data-reset]'?resetButtons:s==='aside input,aside select'?Array.from(elements.values()).filter(e=>['INPUT','SELECT'].includes(e.tagName)):[]};
class BrowserWorker{
 constructor(url){const source=blobs.get(url)?.textValue;if(!source)throw Error('Missing Blob worker');this.thread=new Thread(`const {parentPort}=require('node:worker_threads');globalThis.postMessage=data=>parentPort.postMessage(data);parentPort.on('message',data=>globalThis.onmessage({data}));\n${source}`,{eval:true});workers.add(this);this.thread.on('message',data=>this.onmessage?.({data}));this.thread.on('error',error=>this.onerror?.({message:error.message,preventDefault(){}}));}
 postMessage(data){this.thread.postMessage(data);}terminate(){terminated++;workers.delete(this);return this.thread.terminate();}
}
const sandbox={console,document,window:{devicePixelRatio:1},Blob:LocalBlob,Worker:BrowserWorker,URL:{createObjectURL:b=>{const id='blob:mock/'+(++blobId);blobs.set(id,b);return id;},revokeObjectURL:id=>blobs.delete(id)},Option:function(text,value){const e=new Element('option');e.textContent=text;e.value=String(value);return e;},ResizeObserver:class{observe(){}},setTimeout:(fn,ms)=>{const timer=setTimeout(fn,ms);timer.unref();return timer;},Float64Array,Uint8ClampedArray};
vm.createContext(sandbox);vm.runInContext(script('numerical-engine')+'\n'+script('application')+'\n;globalThis.testAccess={state,plots};',sandbox);
const ui=sandbox.testAccess,$=id=>elements.get(id),results=[];
async function settled(){const deadline=Date.now()+15000;while(ui.state.worker){if(Date.now()>deadline)throw Error('Worker timeout');await new Promise(r=>setTimeout(r,5));}}
async function fire(id,event='click'){$(id).fire(event);await settled();}
async function change(id,value){$(id).value=String(value);await fire(id,'change');}
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS '+name);}catch(error){results.push({name,pass:false,error:error.stack});console.error('FAIL '+name+'\n'+error.stack);}}
(async()=>{
await check('Load built-in sample through parse Worker and compute through analysis Worker',async()=>{await fire('load-sample');assert.equal(ui.state.table.rows.length,4000);assert.equal(ui.state.raw.t.length,4000);assert.equal($('analyze').disabled,false);await fire('analyze');assert.ok(ui.state.result);assert.equal(ui.state.result.peaks[0].frequency,2);assert.ok(ui.state.result.stft);assert.equal($('export-spectrum').disabled,false);assert.equal(ui.plots.history.series.length,2);});
await check('PSD toggle, FFT/PSD CSV payloads, peak and time-history exports',async()=>{await fire('export-spectrum');assert.equal(downloads.at(-1).name,'fft-amplitude.csv');assert.equal(downloads.at(-1).blob.textValue.split('\r\n').length,2002);await change('mode','psd');assert.match(ui.plots.spectrum.config.ylabel,/PSD/);await fire('export-spectrum');assert.equal(downloads.at(-1).name,'welch-psd.csv');assert.match(downloads.at(-1).blob.textValue,/squared_per_Hz/);await fire('export-peaks');assert.match(downloads.at(-1).blob.textValue,/frequency_Hz,period_s/);await fire('export-history');assert.equal(downloads.at(-1).blob.textValue.split('\r\n').length,4001);});
await check('Selected value column changes detected frequency and blocks stale exports',async()=>{const n=downloads.length;await change('value-col',2);assert.equal(ui.state.dirty,true);assert.equal($('export-spectrum').disabled,true);await fire('export-spectrum');assert.equal(downloads.length,n);await fire('analyze');assert.equal(ui.state.result.peaks[0].frequency,5);});
await check('Parameter change marks result dirty and export handler refuses stale data',async()=>{await change('window','hamming');assert.equal(ui.state.dirty,true);const count=downloads.length;await fire('export-spectrum');assert.equal(downloads.length,count);await fire('analyze');assert.equal(ui.state.dirty,false);});
await check('Nonuniform input warns and blocks analysis until resampling enabled',async()=>{await change('sample','irregular');await fire('load-sample');assert.match($('status').textContent,/非等間隔/);await fire('analyze');assert.equal(ui.state.result,null);assert.match($('status').textContent,/Non-uniform/);$('resample').checked=true;await fire('resample','change');await fire('analyze');assert.ok(ui.state.result);assert.ok(ui.state.result.processedSummary.jitter<1e-8);});
await check('Tab/no-header input, non-first time column, millisecond conversion',async()=>{$('paste').value=Array.from({length:1000},(_,i)=>`${Math.sin(2*Math.PI*10*i/1000)}\t${i}\t${2*i}`).join('\n');await fire('load-paste');await change('delimiter','tab');await change('header','no');await change('time-col',1);await change('value-col',0);await change('time-unit',.001);await fire('analyze');assert.ok(ui.state.result);assert.ok(Math.abs(ui.state.result.summary.fs-1000)<1e-8);assert.equal(ui.state.result.peaks[0].frequency,10);});
await check('Malformed and missing selected numeric fields produce explicit errors',async()=>{$('paste').value='t,x\n0,1,2';await fire('load-paste');assert.equal(ui.state.table,null);assert.match($('status').textContent,/column|two/i);await change('delimiter','auto');await change('header','auto');$('paste').value='time,value\n'+Array.from({length:16},(_,i)=>`${i},${i===6?'':i}`).join('\n');await fire('load-paste');assert.match($('status').textContent,/有限の数値/);await fire('analyze');assert.equal(ui.state.result,null);});
await check('Invalid numeric settings and frequency range are reported',async()=>{await change('sample','tones');await fire('load-sample');await change('segment',7);await fire('analyze');assert.equal(ui.state.result,null);assert.match($('status').className,/error/);await change('segment',1024);await fire('analyze');assert.ok(ui.state.result);await change('fmax',0);assert.match($('status').textContent,/上限/);await change('fmax',50);});
await check('Cancel terminates real worker; late completion cannot restore result',async()=>{await fire('window','change');const n=terminated;$('analyze').fire('click');assert.ok(ui.state.worker);await fire('cancel');assert.equal(ui.state.worker,null);assert.equal(ui.state.result,null);assert.equal(ui.state.dirty,true);assert.ok(terminated>n);await new Promise(r=>setTimeout(r,30));assert.equal(ui.state.result,null);});
await check('Integration metadata separates processed and original physical units on dual axes',async()=>{await change('unit','m/s²');await change('integrate',1);await fire('analyze');assert.ok(ui.state.result);assert.ok(ui.plots.history.series[1].right);assert.match(ui.plots.history.config.rightLabel,/s².*s/);assert.equal(ui.plots.spectrum.series.length,2);assert.ok(ui.plots.spectrum.series[1].right);assert.ok(ui.plots.spectrum.rightBase);await fire('export-history');assert.match(downloads.at(-1).blob.textValue.split('\r\n')[0],/processed_\(m\/s²\)·s/);});
await check('Chart event handlers zoom, pan, reset and populate hover text',async()=>{const p=ui.plots.history,base=p.view.slice();await p.canvas.fire('keydown',{key:'+'});assert.ok(p.view[1]-p.view[0]<base[1]-base[0]);await p.canvas.fire('keydown',{key:'ArrowRight'});assert.notEqual(p.view[0],base[0]);await p.canvas.fire('keydown',{key:'Home'});assert.deepEqual(Array.from(p.view),Array.from(p.base));await p.canvas.fire('pointermove',{clientX:p.left+p.pw/2,clientY:p.top+p.ph/2});assert.equal(p.tip.style.display,'block');assert.match(p.tip.textContent,/入力/);});
await check('FRS requires explicit acceleration units and rejects time integration',async()=>{
 await change('integrate',0);$('frs-enable').checked=true;await fire('frs-enable','change');await fire('analyze');assert.equal(ui.state.result,null);assert.match($('status').textContent,/入力加速度単位/);
 await change('frs-unit','g');await change('frs-count',24);await change('frs-min',.5);await change('frs-max',30);await change('integrate',1);await fire('analyze');assert.equal(ui.state.result,null);assert.match($('status').textContent,/積分/);await change('integrate',0);
});
await check('FRS Worker produces multiple damping curves, SI output and complete CSV metadata',async()=>{
 await fire('analyze');assert.ok(ui.state.result?.frs);const r=ui.state.result.frs;assert.equal(r.curves.length,2);assert.equal(r.frequency.length,24);assert.equal(ui.plots.frs.series.length,3);assert.match(ui.plots.frs.config.ylabel,/Absolute acceleration/);assert.equal($('export-frs').disabled,false);assert.equal(pngButtons.find(b=>b.dataset.png==='frs').disabled,false);
 await fire('export-frs');const d=downloads.at(-1);assert.equal(d.name,'floor-response-spectrum.csv');const rows=ui.state.result? sandbox.createEngine().parse(d.blob.textValue,'comma','yes').rows:[];assert.equal(rows.length,48);assert.equal(Number(rows[0][2]),.02);assert.equal(Number(rows[24][2]),.05);const m=JSON.parse(rows[0][9]);assert.equal(m.preprocessing.frs.unit,'g');assert.equal(m.preprocessing.frs.tail,5);assert.ok(m.method.includes('Newmark'));assert.ok(m.pfa>9);assert.equal(Number(rows[0][3]),r.curves[0].sa[0]);
});
await check('FRS response measure, period ordering and log axis switch without recalculation',async()=>{
 const r=ui.state.result.frs;await change('frs-axis','period');await change('frs-measure','psa');assert.equal(ui.state.dirty,false);assert.match(ui.plots.frs.config.xlabel,/period/);assert.match(ui.plots.frs.config.ylabel,/Pseudo acceleration/);assert.ok(ui.plots.frs.series[0].x[0]<ui.plots.frs.series[0].x[23]);assert.equal(ui.plots.frs.series[0].y[0],r.curves[0].psa[23]);await change('frs-measure','sv');assert.equal(ui.plots.frs.series.length,2);assert.match(ui.plots.frs.config.ylabel,/m\/s/);$('frs-log').checked=false;await fire('frs-log','change');assert.equal(ui.plots.frs.config.log,false);assert.equal(ui.state.dirty,false);
});
await check('FRS setting changes block stale CSV and PNG, disabled FRS ignores invalid fields',async()=>{
 await change('frs-damping','0.5, 2, 5');assert.equal(ui.state.dirty,true);assert.equal($('export-frs').disabled,true);assert.equal(pngButtons.find(b=>b.dataset.png==='frs').disabled,true);const count=downloads.length;await fire('export-frs');assert.equal(downloads.length,count);await fire('analyze');assert.equal(ui.state.result.frs.curves.length,3);
 await change('frs-damping','2,');await fire('analyze');assert.equal(ui.state.result,null);assert.match($('status').textContent,/減衰比/);$('frs-enable').checked=false;await fire('frs-enable','change');await fire('analyze');assert.ok(ui.state.result);assert.equal(ui.state.result.frs,null);assert.equal($('export-frs').disabled,true);assert.equal(ui.plots.frs.series.length,0);assert.equal(pngButtons.find(b=>b.dataset.png==='frs').disabled,true);
});
await check('Cancelling FRS terminates Worker and prevents stale result restoration',async()=>{
 await change('frs-damping','2, 5');$('frs-enable').checked=true;await fire('frs-enable','change');$('analyze').fire('click');assert.ok(ui.state.worker);await fire('cancel');assert.equal(ui.state.worker,null);assert.equal(ui.state.result,null);assert.equal($('export-frs').disabled,true);await new Promise(r=>setTimeout(r,30));assert.equal(ui.state.result,null);
});
for(const w of workers)w.terminate();
const passed=results.filter(r=>r.pass).length;
fs.writeFileSync(path.join(__dirname,'UI_VALIDATION.md'),`# DOM event integration validation\n\nExecuted ${new Date().toISOString()}, Node ${process.version}. ${passed}/${results.length} checks passed against the scripts embedded in final \`index.html\`.\n\nThis is **not real-browser GUI verification**. It executes the actual application and numerical scripts in a VM using minimal DOM/canvas mocks. Worker messages execute in real Node worker threads using the actual Blob worker source. Browser local-file permissions, pixel rendering, browser download behavior, accessibility, and cross-browser compatibility remain unverified. No browser or alternative graphical surface was used.\n\n| Check | Result |\n|---|---|\n${results.map(r=>`| ${r.name} | ${r.pass?'PASS':'FAIL'} |`).join('\n')}\n\n${results.filter(r=>!r.pass).map(r=>'```\n'+r.error+'\n```').join('\n')}\nReproduce with \`node tests/ui.test.cjs\`. Canvas operations are mocked; chart tests verify event-driven state and metadata, not visible appearance.\n`);
console.log(`${passed}/${results.length} DOM integration checks passed`);process.exitCode=passed===results.length?0:1;
})().catch(error=>{console.error(error);for(const w of workers)w.terminate();process.exitCode=1;});
